- name: stop gateway service
  when: "'full_node' in group_names"
  become: true
  systemd:
    name: gateway.service
    state: stopped

- name: purge chain
  become: true
  when: "'full_node' in group_names"
  shell: |
    set -o pipefail
    {{ gateway_bin }} purge-chain -y --chain {{ gateway_chain_spec_raw }} --base-path {{ chain_data_dir }}  --database paritydb-experimental
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall Gateway systemd unit file (full node)
  template: src=gateway-full-node.j2 dest=/etc/systemd/system/gateway.service
  become: true
  when: "'full_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags: gateway-service

- name: start gateway service
  when: "'full_node' in group_names"
  become: true
  systemd:
    name: gateway.service
    state: started
    daemon_reload: yes
